version: '3.9'

services:
  runtime:
    container_name: backend_prod
    image: backend_prod:v1
    build:
      context: .
      dockerfile: ./docker/runtime/Dockerfile
      target: prod
    ports:
      - "127.0.0.1:8000:3000"
    environment:
      NODE_ENV: production
