version: '3.9'

services:
  backend:
    image: backend_dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - backend_dev:/app
      - profile:/root
    expose:
      - 3000
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: development
    command: pnpm dev
volumes:
  backend_dev:
