version: '3.9'

services:
  backend:
    container_name: backend_prod
    image: backend:v1
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: prod
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      NODE_ENV: production
