version: '3.9'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - backend:/app
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: production
volumes:
  backend:
