version: '3.9'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - app_dir:/app
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      NODE_ENV: development
volumes:
  app_dir:
